Repository sameerasw/my-internet, pull requests merged in 2025-08, with the labels that each got.

#1617 Update web.whatsapp.com.css
  websites/web.whatsapp.com.css
Labels: Theme

#1654 Allow prefix ambiguity for `pcpartpicker.com`
  websites/+pcpartpicker.com.css
Labels: enhancement, Theme

#1630 Create icon.kitchen.css
  websites/icon.kitchen.css
Labels: Theme

#1724 Rename +hyprland.org.css to +hypr.land.css
  websites/+hypr.land.css
Labels: enhancement

#1720 Create quickshell.org.css
  websites/quickshell.org.css
Labels: Theme

#1682 Update web.whatsapp.com.css
  websites/web.whatsapp.com.css
Labels: enhancement
