Repository sameerasw/my-internet, pull requests merged in 2025-03, with the labels that each got.

#74 kagi.com custom css added
  kagi.com.css
Labels: Theme

#176 Added letterboxd.com.css
  websites/letterboxd.com.css
Labels: enhancement, Theme

#185 Create pepper.pl.css
  websites/pepper.pl.css
Labels: Theme

#186 Create gg.deals.css
  websites/gg.deals.css
Labels: Theme

#207 Better image fade in letterboxd.com.css
  websites/letterboxd.com.css
Labels: enhancement, Theme

#235 Improved Transparency
  websites/backloggd.com.css
Labels: Theme

#240 Added minesweeper.online
  websites/minesweeper.online.css
Labels: Theme

#241 Update demo.jellyfin.org.css
  websites/demo.jellyfin.org.css
Labels: enhancement, Theme

#243 Theme for anilist.co
  websites/anilist.co.css
Labels: enhancement, Theme

#252 Create miruro.to.css
  websites/miruro.to.css
Labels: Theme

#254 Create miruro.online.css
  websites/miruro.online.css
Labels: Theme

#255 Enhanced transparency & effects
  websites/miruro.online.css
  websites/miruro.to.css
Labels: enhancement, Theme

#288 New themes and fix
  styles.json
  websites/fast.com.css
  websites/github.com.css
  websites/huggingface.co.css
  websites/ninite.com.css
Labels: Theme

#298 (Small pull request) Better text input for gemini.google.com.css
  websites/gemini.google.com.css
Labels: Theme

#303 small fix
  websites/gemini.google.com.css
Labels: enhancement

#321 Make Sidebar Transparent (adds option)
  websites/youtube.com.css
Labels: enhancement

#323 Fix Accidental Removal
  websites/youtube.com.css
Labels: bug, enhancement

#357 Added aternos.org
  websites/aternos.org.css
Labels: Theme

#409 Small Update notion.so.css
  websites/notion.so.css
Labels: enhancement

#367 Add style for codeberg
  websites/codeberg.org.css
Labels: Theme

#468 Update old.reddit.com.css for RES users
  websites/old.reddit.com.css
Labels: enhancement, Theme
