Repository sameerasw/my-internet, pull requests merged in 2025-05, with the labels that each got.

#782 Update t3.chat.css
  websites/t3.chat.css
Labels: bug, enhancement

#794 add cubedesk.io.css
  websites/cubedesk.io.css
Labels: Theme

#802 Created echo.uib.no.css
  websites/echo.uib.no.css
Labels: Theme

#665 Create app, blog, cloud, days, docs, forum, id, login, projecthub, se…
  websites/app.arduino.cc.css
  websites/blog.arduino.cc.css
  websites/cloud.arduino.cc.css
  websites/days.arduino.cc.css
  websites/docs.arduino.cc.css
  websites/forum.arduino.cc.css
  websites/id.arduino.cc.css
  websites/login.arduino.cc.css
  websites/projecthub.arduino.cc.css
  websites/search.arduino.cc.css
  websites/store.arduino.cc.css
  websites/www.arduino.cc.css
Labels: Theme

#792 Created yr.no.css
  websites/yr.no.css
Labels: Theme

#743 github fixes. (github.com)
  styles.json
  websites/github.com.css
Labels: enhancement, Theme

#817 Added support for programiz.com
  websites/programiz.com.css
Labels: Theme

#818 Tweaked aternos.org
  websites/aternos.org.css
Labels: Theme

#805 Added support for ilovepdf.com
  websites/ilovepdf.com.css
Labels: Theme

#804 Added support for iloveimg.com
  websites/iloveimg.com.css
Labels: Theme

#848 Create flipkart.com.css
  styles.json
  websites/flipkart.com.css
Labels: Theme

#867 Create track.toggle.com.css
  websites/track.toggl.com.css
Labels: Theme

#803 Added support for login.microsoftonline.com (Microsoft's Login Page)
  websites/login.microsoftonline.com.css
Labels: Theme

#910 Create nebula.tv.css for #899
  websites/nebula.tv.css
Labels: Theme

#906 improvement to calendar.google.com
  websites/calendar.google.com.css
Labels: Theme

#940 Add theme for app.graphite.dev
  websites/app.graphite.dev.css
Labels: Theme

#1013 Add Deer.social theme
  websites/deer.social.css
Labels: Theme

#1119 Added support for codepen.io
  websites/codepen.io.css
Labels: Theme

#1117 feat: remove whatsapp chat background
  websites/web.whatsapp.com.css
Labels: Theme
