Repository sameerasw/my-internet, pull requests merged in 2025-07, with the labels that each got.

#1427 fix a bug with chatgpt theme
  websites/chatgpt.com.css
Labels: bug, Theme

#1424 Create instructables.com.css
  websites/instructables.com.css
Labels: Theme

#1444 Rename bing.com.css to +bing.com.css
  websites/+bing.com.css
Labels: Theme

#1435 Create randomnerdtutorials.com.css
  websites/developer.android.com.css
  websites/instructables.com.css
  websites/randomnerdtutorials.com.css
  websites/w3schools.com.css
  websites/web.whatsapp.com.css
Labels: Theme

#1516 Update linkedin.com.css
  websites/linkedin.com.css
Labels: Theme

#1474 Fix chatgpt sidebar transparency
  websites/chatgpt.com.css
Labels: enhancement

#1525 Starship.rs
  styles.json
  websites/starship.rs.css
Labels: Theme

#1522 Update linkedin.com.css
  websites/linkedin.com.css
Labels: Theme

#1528 implement auto formatting
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/website-theme-request.md
  .github/workflows/check_commits.yml
  .github/workflows/create-pre-release.yml
  .github/workflows/format_repo.yml
  .github/workflows/issue_comment.yml
  .github/workflows/jekyll-gh-pages.yml
  .github/workflows/map-issues.yml
  .github/workflows/pr-comment.yml
  .github/workflows/update-styles-json.yml
  .prettierignore
  .prettierrc.json
Labels: enhancement

#1542 Update developer.android.com.css
  websites/developer.android.com.css
Labels: Theme

#1565 Update accounts.google.com.css
  websites/accounts.google.com.css
Labels: Theme

#1586 Update web.whatsapp.com.css
  websites/web.whatsapp.com.css
Labels: Theme

#1609 Update web.whatsapp.com.css
  websites/web.whatsapp.com.css
Labels: Theme
