Repository sameerasw/my-internet, pull requests merged in 2025-04, with the labels that each got.

#551 create robu.in.css
  websites/robu.in.css
Labels: Theme

#560 Create hubtronics.in.css
  websites/hubtronics.in.css
Labels: Theme

#580 Add custom style for derpibooru.org
  websites/derpibooru.org.css
Labels: Theme

#523 Made bg and borders transparents for standardnotes
  websites/app.standardnotes.com.css
Labels: enhancement

#625 Fixed the grey bar showing above the search bar on roblox.com
  websites/roblox.com.css
Labels: bug, enhancement

#650 Create robokits.co.in.css and robocraze.com.css
  websites/robocraze.com.css
  websites/robokits.co.in.css
Labels: Theme

#672 Update mail.google.com.css
  websites/mail.google.com.css
Labels: enhancement, Theme

#684 Create +buymeacoffee.com.css, www.patreon.com.css, wokwi.com.css, doc…
  websites/+buymeacoffee.com.css
  websites/docs.wokwi.com.css
  websites/wokwi.com.css
  websites/www.patreon.com.css
Labels: Theme

#688 Create +qmk.fm.css and +zmk.dev.css
  websites/+qmk.fm.css
  websites/+zmk.dev.css
Labels: Theme

#777 Derpybooru update
  websites/derpibooru.org.css
Labels: enhancement, Theme
