Repository sameerasw/my-internet, pull requests merged in 2025-06, with the labels that each got.

#1168 Update duckduckgo.com.css
  websites/duckduckgo.com.css
Labels: enhancement, Theme

#1166 Fix Small Typos in README
  README.md
Labels: bug, enhancement

#1156 fix: web.whatsapp transparency
  websites/web.whatsapp.com.css
Labels: enhancement, Theme

#1163 Separate chat.deepseek.com features
  websites/chat.deepseek.com.css
Labels: enhancement, Theme

#1162 Update github.com.css
  websites/github.com.css
Labels: enhancement, Theme

#1189 Add theme for app.todoist.com
  websites/app.todoist.com.css
Labels: Theme

#1186 Add some missing slack selectors
  styles.json
  websites/app.slack.com.css
Labels: Theme

#1181 add theme for inertia.social
  websites/+inertia.social
Labels: Theme

#1227 feat: add vscode to gitignore
  .gitignore
Labels: enhancement

#1246 Add support for dropbox.com
  websites/dropbox.com.css
Labels: Theme

#1277 Update dev.azure.com
  styles.json
  websites/dev.azure.com.css
Labels: bug, enhancement

#1306 feat: make sidebar transparent
  websites/teams.microsoft.com.css
Labels: enhancement, Theme

#1304 feat: make bar inside chat transparent
  websites/+discord.com.css
Labels: enhancement, Theme

#1350 Update developer.android.com.css
  websites/developer.android.com.css
Labels: enhancement, Theme

#1366 feat: fix and improve chat background transparency
  websites/web.whatsapp.com.css
Labels: enhancement

#1361 Create hacyderm.io.css
  websites/hachyderm.io.css
Labels: Theme

#1305 feat: improve outlook office
  websites/outlook.office.com.css
Labels: enhancement, Theme

#1397 add more bsky appviews
  websites/smol.life.css
  websites/zeppelin.social.css
Labels: Theme
